class Variables{
public static void main(String a[]){
String templeName="Kote Anjaneya Swamy Temple";
int noOfPeople=5000;
boolean isCurrentlyOpen=true;
String monthName="April";
int noOfDays=30;
int noOfWeeks=4;
String handwashName="Dettol";
int costOfHandwashName=99;
int ratingOfHandwash=5;
String chocolateName="Dairy Milk Silk";
int costOfChocolate=120;
String sweetName="Kaaju Burfi";
int costOfSweet=50;
boolean isCurrentlyAvailableSweet=true;
String laptopName="Dell Inspiron";
int costOfLaptop=45000;
int ratingOfLaptop=4;
String soapName="Johnsons's Baby Soap";
int costOfSoap=60;
String soapColour="White";
String dryFruits="Pista";
int costOfDryFruits=500;
int ratingOfDryFruits=5;
String bodyLotion="Nivea Body Lotion";
int costOfBodyLotion=120;
String faceCream="Ponds White Beauty";
int costOfFaceCream=120;
Boolean isCurrentlyAvailableFaceCream=true;
String saree="Silk Saree";
int noOfSarees=7;
int costOfSarees=25000;
String addressOfSaree="Jai Nagar";
String fanName="Philips";
int noOfWings=3;
int costOfFan=589;
String washingMachineName="My IFB";
int costOfWashingMachine=38000;
boolean isCurrentlyAvailableWashingMachine=true;
String penName="Doms";
int noOfPens=20;
int costOfPens=60;
String penColour="Black";
String toothPaste="Colgate";
int costOfToothPaste=89;
int weightOfToothPaste=100;
String houseName="Kanasu";
int noOfRoomsHouse=4;
int noOfFloorsHouse=2;
String houseAddress="Shimoga";
String nailPolish="Dazler";
String nailPolishColour="Black";
int costOfNailPolish=85;
String mncName="WIPRO";
int noOfEmployees=209890;
int year=1945;
String payingGuestName="Rakshita PG";
int noOfRoomsPayingGuest=40;
int noOfFloorsPayingGuest=3;
int costOfPayingGuest=6000;
String faceMask="N95";
int costOfFaceMask=100;
int noOfMasks=25;
boolean isCurrentlyAvailableFaceMask=true;
System.out.println(templeName);
System.out.println(noOfPeople);
System.out.println(isCurrentlyOpen);
System.out.println(monthName);
System.out.println(noOfDays);
System.out.println(noOfWeeks);
System.out.println(handwashName);
System.out.println(costOfHandwashName);
System.out.println(ratingOfHandwash);
System.out.println(chocolateName);
System.out.println(costOfChocolate);
System.out.println(sweetName);
System.out.println(costOfSweet);
System.out.println(isCurrentlyAvailableSweet);
System.out.println(laptopName);
System.out.println(costOfLaptop);
System.out.println(ratingOfLaptop);
System.out.println(soapName);
System.out.println(costOfSoap);
System.out.println(soapColour);
System.out.println(dryFruits);
System.out.println(costOfDryFruits);
System.out.println(ratingOfDryFruits);
System.out.println(bodyLotion);
System.out.println(costOfBodyLotion);
System.out.println(faceCream);
System.out.println(costOfFaceCream);
System.out.println(isCurrentlyAvailableFaceCream);
System.out.println(saree);
System.out.println(noOfSarees);
System.out.println(costOfSarees);
System.out.println(addressOfSaree);
System.out.println(fanName);
System.out.println(noOfWings);
System.out.println(costOfFan);
System.out.println(washingMachineName);
System.out.println(costOfWashingMachine);
System.out.println(isCurrentlyAvailableWashingMachine);
System.out.println(penName);
System.out.println(noOfPens);
System.out.println(costOfPens);
System.out.println(penColour);
System.out.println(toothPaste);
System.out.println(costOfToothPaste);
System.out.println(weightOfToothPaste);
System.out.println(houseName);
System.out.println(noOfRoomsHouse);
System.out.println(noOfFloorsHouse);
System.out.println(houseAddress);
System.out.println(nailPolish);
System.out.println(nailPolishColour);
System.out.println(costOfNailPolish);
System.out.println(mncName);
System.out.println(noOfEmployees);
System.out.println(year);
System.out.println(payingGuestName);
System.out.println(noOfRoomsPayingGuest);
System.out.println(noOfFloorsPayingGuest);
System.out.println(costOfPayingGuest);
System.out.println(faceMask);
System.out.println(costOfFaceMask);
System.out.println(noOfMasks);
System.out.println(isCurrentlyAvailableFaceMask);
}
}
